### ISSUE TITLE
loading data without labels?

### ISSUE THREAD

**Issue by edvinsyk** [junyuan-chen/ReadStatTables.jl#25]
Is there currently a way to load the data without the labels? I've found that the LabeledVectors can have some unexpected behavior when working with variables. 

For example, the LabeledVectors behave differently when working with missing values in transform. This might be solvable, but would be a good start to just allow a labels = false option.

**Comment by junyuan-chen** [comment]
@edvinsyk At this moment, there is no such an option, although it should be straightforward to add such an option. For now, the temporary solution is to directly access the values as a regular `Array`. If the data are in a `ReadStatTable`, the `LabeledVector` won't be constructed if the original value for the value label field in the variable-specific metadata is removed. If the data are already in something like a `DataFrame`, then the way to do that is to replace the columns.
