### ISSUE TITLE
Package release

### ISSUE THREAD

**Issue by bkamins** [junyuan-chen/ReadStatTables.jl#9]
Hi @junyuan-chen,

Do you plan to make a release of this package soon?

**Comment by junyuan-chen** [comment]
Hi @bkamins !

I am about to make a PR that contains more breaking changes that will go into the release (v0.2.0). These changes will improve the performance of reading data files substantially.

**Comment by bkamins** [comment]
Great. Can you ping me when this is done. I would test it then and write a blog post at https://bkamins.github.io/ about it. Thank you!

**Comment by junyuan-chen** [comment]
@bkamins Sure. I look forward to that.

**Comment by junyuan-chen** [comment]
@bkamins I am preparing to release `v0.2.0` now.

**Comment by bkamins** [comment]
Thank you!
